services:
  db:
    image: postgres:15.3-alpine3.18
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=djlibrary
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=libadmin123

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d djlibrary" ]
      interval: 10s
      timeout: 5s
      retries: 5


  api:
    build: .
    restart: on-failure
    volumes:
      - type: bind
        source: .
        target: /app
    ports:
      - 8000:8000
    command: ./docker-entrypoint.sh
    depends_on:
      db:
        condition: service_healthy

  redis:
    image: redis:7.2.0-alpine
    ports:
      - 6379:6379
    volumes:
      - redisdata:/data
  celery:
    build: .
    command: celery -A djlibrary worker --loglevel=info
    depends_on:
      - redis
    volumes:
      - .:/app
  celery-beat:
    build: .
    command: celery -A djlibrary beat --loglevel=info
    depends_on:
      - redis
    volumes:
      - .:/app
volumes:
  postgres_data:
  redisdata: