# Generated by Django 4.2.4 on 2023-08-15 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_librarian',
            field=models.BooleanField(default=False),
        ),
    ]
